### ISSUE TITLE
pvCatalog['expiration']

### ISSUE THREAD

**Issue by CGarces** [Varstahl/xbmc#1]
Hi

During my testing I need to get allways new data, now something previously cached.

Can you point me to the correct line of the source code to remove the cache?

**Comment by Varstahl** [comment]
As of this moment you can either [change the TTL in seconds](https://github.com/Varstahl/xbmc/blob/fea1810dab23f3fa5a97f956c668574f181e3893/plugin.video.amazon-test/default.py#L483) (39600 = 11 hours) or remove the cache file manually or through a script (`~/.kodi/userdata/addon_data/plugin.video.amazon-test/cache.json` or its win equivalent). A manual refresh (and cache removal) is planned but if I understood correctly through my afternoon of studying it won't be show up in the menus until there are actually some videos to refresh.

Changing the TTL is the most effective way for your purposes, just remember to get out to the menu and then re-enter the addon to clear it up.
