### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by corna** [Varstahl/xbmc#13]
Kodi returns this error if I try to sign in:

`````
Traceback (most recent call last):
  File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 43, in <module>
    userAcceptLanguages = '{0}, en-gb;q=0.8, en;q=0.6'.format(re.sub('_','-',Language.lower()))
AttributeError: 'NoneType' object has no attribute 'lower'
`````

apparently [locale.getdefaultlocale()](https://github.com/Varstahl/xbmc/blob/master/plugin.video.amazon-test/default.py#L37) returns a `(None, None)` tuple on my system (RPi 3 with LibreELEC 18, latest build, italian localization).

Having `(None, None)` as default locale seems to me someone's else bug, but at least we should check for its validity with a:

`````
If Language:
    userAcceptLanguages = '{0}, en-gb;q=0.2, en;q=0.1'.format(re.sub('_','-',Language.lower()))
else:
    userAcceptLanguages = 'en-gb;q=0.2, en;q=0.1'
`````

Btw, thanks for your work.

**Comment by Varstahl** [comment]
Fixed in ad1fdee77d5ef3e680089747e76d1c3479b3d609

**Comment by corna** [comment]
This is my LibreELEC locale:
```
LibreELEC:~ # locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
I don't think we should rely on the default locale, on LibreELEC it probably always return `(None, None)`.

**Comment by Varstahl** [comment]
Yeah, we don't, we just use it where we can, it's no big deal.

**Comment by CGarces** [comment]
@corna LibreELEC by default don't provide locale information.
You need to install service.locale addon if you really need it.
