### ISSUE TITLE
primevideo latinamerican

### ISSUE THREAD

**Issue by thetruemachine** [Varstahl/xbmc#17]
Excellent work. 
Could you in the not too distant future make it work with primevideo latinamerican?

**Comment by Varstahl** [comment]
Duplicate of https://github.com/Sandmann79/xbmc/issues/22, it already does. The update for PrimeVideo support will be pushed in a few days, we are currently fixing the last couple things.

Unless you are aware of bugs that make it currently not work for latinamericans, I'll just assume it does.

**Comment by thetruemachine** [comment]
Thanks.
